config/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myShop/',include('shop.urls',namespace='shop')),
   
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/shop/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

from .views import ProductListView,ProductCreateView,ProductDeleteView,ProductEditView, CateoryListView

app_name = 'shop'

urlpatterns = [
    path('',include('django.contrib.auth.urls')),
    
    path('home/', ProductListView.as_view(), name='home'),
    path('add_product/', ProductCreateView.as_view(), name='add_product'),
    path('product/<int:pk>/delete/', ProductDeleteView.as_view(),name='product_delete'),
    path('product/<int:pk>/edit/', ProductEditView.as_view(),name='edit'),
    path('category-product-list/<int:cat_id>/', views.category_product_list,name='category-product-list'),
    path('category-list/', views.CateoryListView.as_view(),name='category-list'),
    
    # path('api/products/', views.get_products, name='get_products'),
# 
]

config/shop/models.py
from django.db import models

# Create your models here.



class Category(models.Model):
    name = models.CharField(max_length=200)
    image = models.ImageField(upload_to='item_images', null=True)
   
    slug = models.SlugField(max_length=200,unique=True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['name']),
        ]
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name
    
class Product(models.Model):
    category = models.ForeignKey(Category,related_name='products',
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    image = models.ImageField(upload_to='item_images')
    
    new_price = models.DecimalField(max_digits=10,decimal_places=2,null=False,default=0.00)
    old_price = models.DecimalField(max_digits=20,decimal_places=2,null=False)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['id','slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created'])
        ]

    def __str__(self):
        return self.name

config/shop/forms.py
from django import forms
from .models import Product, Category

from django.contrib.auth.models import User

class AddProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name','category','image','new_price','old_price']
        widgets = {

            'name':forms.TextInput(attrs={
                'class':'form-control'
            }),

            'category':forms.Select(attrs={
                'class':'form-control'
            }),

            
            'image':forms.FileInput(attrs={
                'accept': 'image/*',
                'class':'form-control'
                
            }),

            'new_price':forms.NumberInput(attrs={
                'class':'form-control'
            }),

            'old_price':forms.NumberInput(attrs={
                'class':'form-control'
            }),
                

           


        
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)
        self.fields['category'].queryset = Category.objects.all()

   

class EditProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name','image','new_price']
        widgets = {
            'image':forms.FileInput(attrs={
                'accept': 'image/*'
            })
        }




class SearchForm(forms.Form):
    query = forms.CharField(label='Search', max_length=100)

    

config/shop/views.py
from django.shortcuts import render
from django.views.generic import ListView,CreateView,DeleteView,UpdateView
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.utils.decorators import method_decorator
from .models import Product, Category


from django.db.models import Q
from .forms import AddProductForm,EditProductForm
from django.urls import reverse_lazy


# Create your views here.




class ProductListView(ListView):
    model = Product
   

    template_name = 'shop/home.html'
    context_object_name = 'products'
    

# class LaptopListView(ListView):
#     model =  Category
#     template_name = 'shop/home.html'
#     context_object_name = 'categories'

@method_decorator(login_required,name='dispatch')
@method_decorator(staff_member_required,name='dispatch')
class ProductCreateView(CreateView):
    model = Product
    form_class = AddProductForm
    success_url = reverse_lazy('shop:home')
    template_name = 'shop/add_products.html'

@method_decorator(login_required,name='dispatch')
@method_decorator(staff_member_required,name='dispatch')
class ProductEditView(UpdateView):
    model = Product
    form_class = AddProductForm
    success_url = reverse_lazy('shop:home')
    template_name = 'shop/add_products.html'
    

@method_decorator(login_required,name='dispatch')
@method_decorator(staff_member_required,name='dispatch')
class ProductDeleteView(DeleteView):
    model = Product
    template_name = 'shop/product_confirm_delete.html'
    success_url = reverse_lazy('shop:home')


        
    
   



class CateoryListView(ListView):
    model = Category
    template_name = 'shop/category_list.html'
    context_object_name = 'category'


def category_product_list(request, cat_id):
    category = Category.objects.get(id=cat_id)
    data = Product.objects.filter(category=category).order_by('-id')
    return render(request, 'shop/category_product_list.html',{'data':data})

config/shop/templates/shop/add_products.html
{% extends 'shop/base.html' %}


{% block title %} Add Product {% endblock title  %}

{% block content %}
    <!-- <form action="" id="categoryForm"></form> -->
<div class="container">

    <div class="form-group">

        <form action="" method="post" enctype="multipart/form-data" id="categoryForm">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary ">Add Product</button>
           
    </div>
      

        <!-- <input type="submit" value="Add Product"> -->
    </form>
</div>
{% endblock %}

config/shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

    <title>{% block title %} Et HAIZ-MOBILE {% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-secondary" id="navbar_top">
        <div class="container">
            <a href="{% url 'shop:home' %}" class="navbar-brand">
                <img src="{% static 'images/favicon.ico' %}" alt="logo" height="50px" width="50px">
                ET_HAIZ MOBILE
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">

                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a href="{% url 'shop:home' %}" class="nav-link">Home</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'shop:login' %}" class="nav-link">Login</a>
                    </li>
                    {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{% url 'shop:add_product' %}" class="nav-link">Add Product</a>
                    </li>

                    <li class="nav-item">
                        <a href="{% url 'shop:logout' %}" class="nav-link">Log out</a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        <a href="{% url 'shop:category-list' %}" class="nav-link">Categories</a>
                    </li>
                    <li class="nav-item dropdown d-block d-md-none">
                        <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown">
                            Accounts
                        </a>
                        <ul class="dropdown-menu">
                           <li><a class="dropdown-item"  href="{% url 'shop:login' %}">Login</a></li> 
                        </ul>

                    </li>

                </ul>
            </div>
        </div>
    </nav>
    
    <div class="container-fluid">
        {% block content %}
        {% endblock %}

    </div>
    
    <footer class="bg-secondary text-white py-2 mt-5">
        <div class="container  text-center ">
            <div class="row">
                <div class="col">
                    <a href="https://www.facebook.com/profile.php?id=100068391200281&mibextid=tzlV2A" 
                    class="text-white me-3"><i class="fab fa-facebook-f fa-2x"></i></a>
                    <a href="https://wa.me/message/SJVLQKH5XBR2L1"
                     class="text-white me-3"><i class="fab fa-whatsapp fa-2x"></i></a>
                    <a href="mailto:ethaizmobile@gmail.com" class="text-white me-3"><i class="fas fa-envelope fa-2x"></i></a>
                </div>
            </div>
            <p class="display-5 mb-3"> ET_HAIZ MOBILE</p>
            <small class="text-light">
                 <p>Since July 2017</p>
                Copyright &copy:  <script>document.write(new Date().getFullYear())</script> Et_haiz

            </small>
        </div>
    </footer>
   
            

    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>
</body>
</html>

config/shop/templates/shop/category_list.html
{% extends 'shop/base.html' %}
{% load static %}

{% block content %}
<main class="container my-4">
    <h3 class="my-4 border-bottom pb-1 text-dark">Categories</h3>
    <div class="row">
        
            {% for cat in category %}
            <div class="col-md-3 mb-4">
                    <div class="card shadow">

                        <a href="{% url 'shop:category-product-list' cat.id %}"> <img src="{{ cat.image.url  }}" alt="{{ cat.name }}" class="card-img-top"></a>
                        <div class="card-body">
                            <h6 class="card-text">{{ cat.name }}</h6>
                        </div>
                    </div>
            </div>
            {% endfor %}
        
    </div>
</main>
{% endblock %} 

config/shop/templates/shop/category_product_list.html
{% extends 'shop/base.html' %}
{% load static %}

{% block content %}
<section>
  <div class="container">
    <div class="row" id="product-list">
      {% for product in data%}
      <div class="col-md-4">
        <div class="card mb-4">
          <img src="{{ product.image.url }}" alt="{{ product.name }}" class="card-image-top">
          <div class="card-body text-center">
            <h5 class="card-title">{{ product.name }}</h5>
            <div class="price">
              <p class="card-text font-weight-bold">#{{ product.new_price}}</p>
              <p class="card-text font-muted"><del>#{{ product.old_price}}</del></p>
            </div>
          </div>
          {% if request.user.is_authenticaated %}
            <div class="container">
              <div class="row justify-content-center">
                <div class="col-sm-auto">
                  <a href="{% url 'shop:product_delete' producct.id %}">
                    <button class="btn btn-warning">Remove</button>
                  </a>
                  
                </div>

                <div class="col-sm-auto">
                  <a href="{% url 'shop:edit' product.id %}">
                    <button class="btn btn-primary">Edit</button>
                  </a>
                  
                </div>
              </div>
            </div>
          {% endif %}
        </div>
      </div>
    {% endfor %}
    </div>

  </div>
    
  </section>



{% endblock %}

config/shop/templates/shop/home.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %} Welcome {% endblock %}
{% block content %}



    <!-- slideshow -->
    <section id="slideshow">
        <div>
            <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel" data-bs-interval="2000">
                <div class="carousel-inner">
                  <div class="carousel-item active">
                    <img class="slide-show" src="{% static 'images/image1.jpg' %}" height="200px" width="500px" alt="gadget">
                    GADGETS
                    
                  </div>
                  <div class="carousel-item">
                    <img class="slide-show" src="{% static 'images/appleiwatch3.jpg' %}" height="200px" width="500px" alt="gadget">
                    APPLE IWATCH
                  </div>
                  <div class="carousel-item">
                    <img class="slide-show" src="{% static 'images/carops5.jpg' %}" height="200px" width="500px" alt="gadget">
                    PLAY STATION
                  </div>
                  <div class="carousel-item">
                    <img class="slide-show" src="{% static 'images/carotv1 - Copy.jpg' %}" height="200px" width="500px" alt="gadget">
                    TELEVISIONS
                  </div>
                  <div class="carousel-item">
                    <img class="slide-show" src="{% static 'images/caromacbook.jpg' %}" height="200px" width="500px" alt="gadget">
                    MACBOOKS
                  </div>
                  <div class="carousel-item">
                    <img class="slide-show" src="{% static 'images/image6.jpg' %}" height="200px" width="500px" alt="gadget">
                    ACCESSORIES
                  </div>
                  <div class="carousel-item">
                    <img class="slide-show" src="{% static 'images/caroiphone.jpg' %}" height="200px" width="500px" alt="gadget">
                    IPHONES
                  </div>
                  <div class="carousel-item">
                    <img class="slide-show" src="{% static 'images/image8.jpg' %}" height="200px" width="500px" alt="gadget">
                    LAPTOPS
                  </div>
                </div>
              </div>
         </section>
        </div>

            <!-- Product display sections -->
           
            <!-- Products section -->
            <section>

              <div class="container">
                <div class="row" id="product-list">
                  {% for product in products %}
                  <div class="col-md-4">
                    <div class="card mb-4">
                      <img src="{{ product.image.url }}" class="card-img-top" alt="{{ product.name }}" width="200" height="200" >
                      <div class="card-body text-center">
                        
                        <h5 class="card-title"> {{ product.name }}</h5>
                        <div class="price">
                          <p class="card-text font-weight-bold">$ {{ product.new_price }}</p>
                          <p class="card-text text-muted"><del>${{ product.old_price}}</del></p>

                        </div>

                        
                      </div>
                      {% if request.user.is_authenticated %}
                      <div class="container">
                        <div class="row justify-content-center">

                          <div class="col-sm-auto">
    
                            <a href="{% url 'shop:product_delete' product.id %}">
                              <button class="btn btn-warning " >Remove</button>
                            </a>
                          </div>
                          <div class=" col-sm-auto">
    
                            <a href="{% url 'shop:edit' product.id %}">
                              <button class="btn btn-primary">Edit</button>
                            </a>
                          </div>
                        </div>
                      </div>
                      {% endif %}
                    </div>
                  </div>
                  {% endfor %}
            </section>
              
            
{% endblock %}

config/shop/templates/shop/product_confirm_delete.html
{% extends 'shop/base.html' %}
{% block title %} Delete Product {% endblock title %}

{% block content %}
<div class="container mt-5">

    <h2 class="pb-5">Are you sure you wannaa delete this</h2>
    <form action="" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Delete</button>
        <a href="{% url 'shop:home' %}" class="btn btn-primary">Cancel</a>
    </form>
</div>
{% endblock %}